//
//  SeasonFactory.swift
//  Westeros
//
//  Created by Sergio Marrero Fernandez on 7/28/17.
//  Copyright © 2017 Keepcoding. All rights reserved.
//

import Foundation


protocol SeasonFactory {
    
    typealias SeasonFilter = (Season) -> Bool
    
    var seasons: [Season] { get }
    
    func season(named: String) -> Season?
    
    func seasons(filteredBy: SeasonFilter) -> [Season]
}

extension LocalFactory: SeasonFactory {
    var seasons: [Season] {
        // Seasons
        let season1 = Season(name: "Season 1", releaseDate: Date.fromString(date: "2011/04/17")!, poster: #imageLiteral(resourceName: "season1.jpg"), overview: "Trouble is brewing in the Seven Kingdoms of Westeros. For the driven inhabitants of this visionary world, control of Westeros' Iron Throne holds the lure of great power. But in a land where the seasons can last a lifetime, winter is coming...and beyond the Great Wall that protects them, an ancient evil has returned. In Season One, the story centers on three primary areas: the Stark and the Lannister families, whose designs on controlling the throne threaten a tenuous peace; the dragon princess Daenerys, heir to the former dynasty, who waits just over the Narrow Sea with her malevolent brother Viserys; and the Great Wall--a massive barrier of ice where a forgotten danger is stirring.")
        let season2 = Season(name: "Season 2", releaseDate: Date.fromString(date: "2012/04/01")!, poster: #imageLiteral(resourceName: "season2.jpg"), overview: "The cold winds of winter are rising in Westeros...war is coming...and five kings continue their savage quest for control of the all-powerful Iron Throne. With winter fast approaching, the coveted Iron Throne is occupied by the cruel Joffrey, counseled by his conniving mother Cersei and uncle Tyrion. But the Lannister hold on the Throne is under assault on many fronts. Meanwhile, a new leader is rising among the wildings outside the Great Wall, adding new perils for Jon Snow and the order of the Night's Watch.")
        let season3 = Season(name: "Season 3", releaseDate: Date.fromString(date: "2013/03/31")!, poster: #imageLiteral(resourceName: "season3.jpg"), overview: "Duplicity and treachery...nobility and honor...conquest and triumph...and, of course, dragons. In Season 3, family and loyalty are the overarching themes as many critical storylines from the first two seasons come to a brutal head. Meanwhile, the Lannisters maintain their hold on King's Landing, though stirrings in the North threaten to alter the balance of power; Robb Stark, King of the North, faces a major calamity as he tries to build on his victories; a massive army of wildlings led by Mance Rayder march for the Wall; and Daenerys Targaryen--reunited with her dragons--attempts to raise an army in her quest for the Iron Throne.")
        let season4 = Season(name: "Season 4", releaseDate: Date.fromString(date: "2014/04/06")!, poster: #imageLiteral(resourceName: "season4.jpg"), overview: "The War of the Five Kings is drawing to a close, but new intrigues and plots are in motion, and the surviving factions must contend with enemies not only outside their ranks, but within.")
        let season5 = Season(name: "Season 5", releaseDate: Date.fromString(date: "2015/04/12")!, poster: #imageLiteral(resourceName: "season5.jpg"), overview: "The War of the Five Kings, once thought to be drawing to a close, is instead entering a new and more chaotic phase. Westeros is on the brink of collapse, and many are seizing what they can while the realm implodes, like a corpse making a feast for crows.")
        let season6 = Season(name: "Season 6", releaseDate: Date.fromString(date: "2016/04/24")!, poster: #imageLiteral(resourceName: "season6.jpg"), overview: "Following the shocking developments at the conclusion of season five, survivors from all parts of Westeros and Essos regroup to press forward, inexorably, towards their uncertain individual fates. Familiar faces will forge new alliances to bolster their strategic chances at survival, while new characters will emerge to challenge the balance of power in the east, west, north and south.")
        let season7 = Season(name: "Season 7", releaseDate: Date.fromString(date: "2017/07/16")!, poster: #imageLiteral(resourceName: "season7.jpg"), overview: "")
    
        
        season1.add(episodes:
            Episode(name: "Winter Is Coming", overview: "Jon Arryn, the Hand of the King, is dead. King Robert Baratheon plans to ask his oldest friend, Eddard Stark, to take Jon's place. Across the sea, Viserys Targaryen plans to wed his sister to a nomadic warlord in exchange for an army.", airDate: Date.fromString(date: "2011/04/17")!, poster:#imageLiteral(resourceName: "episode1x01.jpg"), season: season1),
            Episode(name: "The Kingsroad", overview: "While Bran recovers from his fall, Ned takes only his daughters to Kings Landing. Jon Snow goes with his uncle Benjen to The Wall. Tyrion joins them.", airDate: Date.fromString(date: "2011/04/24")!, poster:#imageLiteral(resourceName: "episode1x02.jpg"), season: season1),
            Episode(name: "Lord Snow", overview: "Lord Stark and his daughters arrive at King's Landing to discover the intrigues of the king's realm.", airDate: Date.fromString(date: "2011/05/01")!, poster:#imageLiteral(resourceName: "episode1x03.jpg"), season: season1),
            Episode(name: "Cripples, Bastards, and Broken Things", overview: "Eddard investigates Jon Arryn's murder. Jon befriends Samwell Tarly, a coward who has come to join the Night's Watch.", airDate: Date.fromString(date: "2011/05/08")!, poster:#imageLiteral(resourceName: "episode1x04.jpg"), season: season1),
            Episode(name: "The Wolf and the Lion", overview: "Catelyn has captured Tyrion and plans to bring him to her sister, Lysa Arryn, at The Vale, to be tried for his, supposed, crimes against Bran. Robert plans to have Daenerys killed, but Eddard refuses to be a part of it and quits.", airDate: Date.fromString(date: "2011/05/15")!, poster:#imageLiteral(resourceName: "episode1x05.jpg"), season: season1),
            Episode(name: "A Golden Crown", overview: "While recovering from his battle with Jamie, Eddard is forced to run the kingdom while Robert goes hunting. Tyrion demands a trial by combat for his freedom. Viserys is losing his patience with Drogo.", airDate: Date.fromString(date: "2011/05/22")!, poster:#imageLiteral(resourceName: "episode1x06.jpg"), season: season1),
            Episode(name: "You Win or You Die", overview: "Robert has been injured while hunting and is dying. Jon and the others finally take their vows to the Night's Watch. A man, sent by Robert, is captured for trying to poison Daenerys. Furious, Drogo vows to attack the Seven Kingdoms.", airDate: Date.fromString(date: "2011/05/29")!, poster:#imageLiteral(resourceName: "episode1x07.jpg"), season: season1),
            Episode(name: "The Pointy End", overview: "Eddard and his men are betrayed and captured by the Lannisters. When word reaches Robb, he plans to go to war to rescue them. The White Walkers attack The Wall. Tyrion returns to his father with some new friends.", airDate: Date.fromString(date: "2011/06/05")!, poster:#imageLiteral(resourceName: "episode1x08.jpg"), season: season1),
            Episode(name: "Baelor", overview: "Robb goes to war against the Lannisters. Jon finds himself struggling on deciding if his place is with Robb or the Night's Watch. Drogo has fallen ill from a fresh battle wound. Daenerys is desperate to save him.", airDate: Date.fromString(date: "2011/06/12")!, poster:#imageLiteral(resourceName: "episode1x09.jpg"), season: season1),
            Episode(name: "Fire and Blood", overview: "With Ned dead, Robb vows to get revenge on the Lannisters. Jon must officially decide if his place is with Robb or the Night's Watch. Daenerys says her final goodbye to Drogo.", airDate: Date.fromString(date: "2011/06/19")!, poster:#imageLiteral(resourceName: "episode1x10.jpg"), season: season1)
        )
        
        season2.add(episodes:
            Episode(name: "The North Remembers", overview: "As Robb Stark and his northern army continue the war against the Lannisters, Tyrion arrives in King’s Landing to counsel Joffrey and temper the young king’s excesses.  On the island of Dragonstone, Stannis Baratheon plots an invasion to claim his late brother’s throne, allying himself with the fiery Melisandre, a strange priestess of a stranger god.  Across the sea, Daenerys, her three young dragons, and the khalasar trek through the Red Waste in search of allies, or water.  In the North, Bran presides over a threadbare Winterfell, while beyond the Wall, Jon Snow and the Night’s Watch must shelter with a devious wildling.", airDate: Date.fromString(date: "2012/04/01")!, poster:#imageLiteral(resourceName: "episode2x01.jpg"), season: season2),
            Episode(name: "The Night Lands", overview: "In the wake of a bloody purge in the capital, Tyrion chastens Cersei for alienating the king’s subjects.  On the road north, Arya shares a secret with Gendry, a Night’s Watch recruit.  With supplies dwindling, one of Dany’s scouts returns with news of their position.  After nine years as a Stark ward, Theon Greyjoy reunites with his father Balon, who wants to restore the ancient Kingdom of the Iron Islands.  Davos enlists Salladhor Saan, a pirate, to join forces with Stannis and Melisandre for a naval invasion of King’s Landing.", airDate: Date.fromString(date: "2012/04/08")!, poster:#imageLiteral(resourceName: "episode2x02.jpg"), season: season2),
            Episode(name: "What is Dead May Never Die", overview: "At the Red Keep, Tyrion plots three alliances through the promise of marriage.  Catelyn arrives in the Stormlands to forge an alliance of her own, but King Renly, his new wife Margaery, and her brother Loras Tyrell have other plans.  At Winterfell, Luwin tries to decipher Bran’s dreams.", airDate: Date.fromString(date: "2012/04/15")!, poster:#imageLiteral(resourceName: "episode2x03.jpg"), season: season2),
            Episode(name: "Garden of Bones", overview: "Joffrey punishes Sansa for Robb’s victories, and Tyrion scrambles to temper the king’s cruelty. Catelyn entreats Stannis and Renly to unite against the Lannisters. Dany and her khalasar arrive at the prosperous city of Qarth. Tyrion coerces a relative into being his eyes and ears. Arya and Gendry are taken to Harrenhal, where their lives are in the hands of Ser Gregor Clegane. Stannis orders Davos to smuggle Melisandre into a secret cove.", airDate: Date.fromString(date: "2012/04/22")!, poster:#imageLiteral(resourceName: "episode2x04.jpg"), season: season2),
            Episode(name: "The Ghost of Harrenhal", overview: "The Baratheon rivalry ends, driving Catelyn to flee and Littlefinger to act. At King’s Landing, Tyrion’s source alerts him to Joffrey’s defense plan - and a mysterious secret weapon. Theon sails to the Stony Shore to prove he’s worthy to be called Ironborn. At Harrenhal, Arya receives a promise from Jaqen H’ghar, one of the prisoners she saved from the Gold Cloaks. The Night’s Watch arrive at the Fist of the First Men, an ancient ringfort where they hope to stem the wildings' advance.", airDate: Date.fromString(date: "2012/04/29")!, poster:#imageLiteral(resourceName: "episode2x05.jpg"), season: season2),
            Episode(name: "The Old Gods and the New", overview: "Theon completes his master stroke. In King's Landing, the Lannisters send Myrcella off to be married. Arya comes face to face with a surprise visitor. Dany vows to take what is hers. Robb and Catelyn receive crucial news. Qhorin gives Jon a chance to prove himself.", airDate: Date.fromString(date: "2012/05/06")!, poster:#imageLiteral(resourceName: "episode2x06.jpg"), season: season2),
            Episode(name: "A Man Without Honor", overview: "Jamie meets a distant relative. Daenerys receives an invitation to the House of the Undying. Theon leads a search party. Jon loses his way in the wilderness. Cersei counsels Sansa.", airDate: Date.fromString(date: "2012/05/13")!, poster:#imageLiteral(resourceName: "episode2x07.jpg"), season: season2),
            Episode(name: "The Prince of Winterfell", overview: "Theon receives a visitor. Arya asks her third and last death from Jaqen. While Stannis' army is reaching its destination, Davos is offered a reward.  Betrayal befalls Robb.", airDate: Date.fromString(date: "2012/05/20")!, poster:#imageLiteral(resourceName: "episode2x08.jpg"), season: season2),
            Episode(name: "Blackwater", overview: "Tyrion and the Lannisters fight for their lives as Stannis’ fleet assaults King’s Landing.", airDate: Date.fromString(date: "2012/05/27")!, poster:#imageLiteral(resourceName: "episode2x09.jpg"), season: season2),
            Episode(name: "Valar Morghulis", overview: "Tyrion awakens to a changed situation. King Joffrey doles out rewards to his subjects. As Theon stirs his men to action, Luwin offers some final advice. Brienne silences Jaime. Arya receives a gift from Jaqen. Dany goes to a strange place. Jon proves himself to Qhorin.", airDate: Date.fromString(date: "2012/06/03")!, poster:#imageLiteral(resourceName: "episode2x10.jpg"), season: season2)
        )
        
        season3.add(episodes:
            Episode(name: "Valar Dohaeris", overview: "Jon meets the King-Beyond-the-Wall while his Night Watch Brothers flee south. In King's Landing, Tyrion wants a reward, Margaery shows her charitable nature, Cersei arranges a dinner party, and Littlefinger offers to help Sansa. Across the Narrow Sea, Daenerys starts her journey west.", airDate: Date.fromString(date: "2013/03/31")!, poster:#imageLiteral(resourceName: "episode3x01.jpg"), season: season3),
            Episode(name: "Dark Wings, Dark Words", overview: "Sansa says too much. Shae asks Tyrion for a favor. Jaime finds a way to pass the time, while Arya encounters the Brotherhood Without Banners.", airDate: Date.fromString(date: "2013/04/07")!, poster:#imageLiteral(resourceName: "episode3x02.jpg"), season: season3),
            Episode(name: "Walk of Punishment", overview: "Tyrion shoulders new responsibilities. Jon is taken to the Fist of the First Men. Daenerys meets with the slavers. Jaime strikes a deal with his captors.", airDate: Date.fromString(date: "2013/04/14")!, poster:#imageLiteral(resourceName: "episode3x03.jpg"), season: season3),
            Episode(name: "And Now His Watch Is Ended", overview: "Trouble brews among the Night's Watch at Craster's. Margaery takes Joffrey out of his comfort zone. Arya meets the leader of the Brotherhood. Varys plots revenge on an old foe. Theon mournfully recalls his missteps. Daenerys deftly orchestrates her exit from Astapor.", airDate: Date.fromString(date: "2013/04/21")!, poster:#imageLiteral(resourceName: "episode3x04.jpg"), season: season3),
            Episode(name: "Kissed by Fire", overview: "The Hound is judged by the gods. Jaime is judged by men. Jon proves himself. Robb is betrayed. Tyrion learns the cost of weddings.", airDate: Date.fromString(date: "2013/04/28")!, poster:#imageLiteral(resourceName: "episode3x05.jpg"), season: season3),
            Episode(name: "The Climb", overview: "Tywin plans strategic unions for the Lannisters. Melisandre pays a visit to the Riverlands. Robb weighs a compromise to repair his alliance with House Frey. Roose Bolton decides what to do with Jaime Lannister. Jon, Ygritte, and the Wildlings face a daunting climb.", airDate: Date.fromString(date: "2013/05/05")!, poster:#imageLiteral(resourceName: "episode3x06.jpg"), season: season3),
            Episode(name: "The Bear and the Maiden Fair", overview: "Daenerys exchanges gifts with a slave lord outside of Yunkai. As Sansa frets about her prospects, Shae chafes at Tyrion’s new situation. Tywin counsels the king, and Melisandre reveals a secret to Gendry. Brienne faces a formidable foe in Harrenhal.", airDate: Date.fromString(date: "2013/05/12")!, poster:#imageLiteral(resourceName: "episode3x07.jpg"), season: season3),
            Episode(name: "Second Sons", overview: "King’s Landing hosts a wedding, and Tyrion and Sansa spend the night together. Daenerys meets the Titan’s Bastard. Davos demands proof from Melisandre. Sam and Gilly meet an older gentleman.", airDate: Date.fromString(date: "2013/05/19")!, poster:#imageLiteral(resourceName: "episode3x08.jpg"), season: season3),
            Episode(name: "The Rains of Castamere", overview: "Robb presents himself to Walder Frey, and Edmure meets his bride. Jon faces his harshest test yet. Bran discovers a new gift. Daario and Jorah debate how to take Yunkai. House Frey joins with House Tully.", airDate: Date.fromString(date: "2013/06/02")!, poster:#imageLiteral(resourceName: "episode3x09.jpg"), season: season3),
            Episode(name: "Mhysa", overview: "Joffrey challenges Tywin. Bran tells a ghost story. In Dragonstone, mercy comes from strange quarters. Daenerys waits to see if she is a conqueror or a liberator.", airDate: Date.fromString(date: "2013/06/09")!, poster:#imageLiteral(resourceName: "episode3x10.jpg"), season: season3)
        )
        
        season4.add(episodes:
            Episode(name: "Two Swords", overview: "Tyrion welcomes a guest to King’s Landing. At Castle Black, Jon Snow finds himself unwelcome. Dany is pointed to Meereen, the mother of all slave cities. Arya runs into an old friend.", airDate: Date.fromString(date: "2014/04/06")!, poster:#imageLiteral(resourceName: "episode4x01.jpg"), season: season4),
            Episode(name: "The Lion and the Rose", overview: "Tyrion lends Jaime a hand. Joffrey and Margaery host a breakfast. At Dragonstone, Stannis loses patience with Davos. Ramsay finds a purpose for his pet. North of the Wall, Bran sees where they must go.", airDate: Date.fromString(date: "2014/04/13")!, poster:#imageLiteral(resourceName: "episode4x02.jpg"), season: season4),
            Episode(name: "Breaker of Chains", overview: "Tyrion ponders his options. Tywin extends an olive branch. Sam realizes Castle Black isn’t safe, and Jon proposes a bold plan. The Hound teaches Arya the way things are. Dany chooses her champion.", airDate: Date.fromString(date: "2014/04/20")!, poster:#imageLiteral(resourceName: "episode4x03.jpg"), season: season4),
            Episode(name: "Oathkeeper", overview: "Dany balances justice and mercy. Jaime tasks Brienne with his honor. Jon secures volunteers while Bran, Jojen, Meera and Hodor stumble on shelter.", airDate: Date.fromString(date: "2014/04/27")!, poster:#imageLiteral(resourceName: "episode4x04.jpg"), season: season4),
            Episode(name: "First of His Name", overview: "Cersei and Tywin plan the Crown's next move; Dany discusses future plans; Jon Snow begins a new mission.", airDate: Date.fromString(date: "2014/05/04")!, poster:#imageLiteral(resourceName: "episode4x05.jpg"), season: season4),
            Episode(name: "The Laws of Gods and Men", overview: "Stannis and Davos set sail; Dany meets with supplicants; Tyrion faces down his father. ", airDate: Date.fromString(date: "2014/05/11")!, poster:#imageLiteral(resourceName: "episode4x06.jpg"), season: season4),
            Episode(name: "Mockingbird", overview: "Tyrion gains an unlikely ally; Daario asks Dany to allow him to do what he does best; Jon's warnings about the vulnerability of the Wall are ignored; Brienne follows a new lead. ", airDate: Date.fromString(date: "2014/05/18")!, poster:#imageLiteral(resourceName: "episode4x07.jpg"), season: season4),
            Episode(name: "The Mountain and the Viper", overview: "Unexpected visitors arrive in Mole's Town. Littlefinger's motives are questioned. Ramsay tries to prove himself to his father. Tyrion's fate is decided.", airDate: Date.fromString(date: "2014/06/01")!, poster:#imageLiteral(resourceName: "episode4x08.jpg"), season: season4),
            Episode(name: "The Watchers on the Wall", overview: "Jon Snow and the Night's Watch face a big challenge.", airDate: Date.fromString(date: "2014/06/08")!, poster:#imageLiteral(resourceName: "episode4x09.jpg"), season: season4),
            Episode(name: "The Children", overview: "Circumstances change after an unexpected arrival from north of the Wall. Dany must face harsh realities. Bran learns more about his destiny. Tyrion sees the truth about his situation.", airDate: Date.fromString(date: "2014/06/15")!, poster:#imageLiteral(resourceName: "episode4x10.jpg"), season: season4)
        )
        
        season5.add(episodes:
            Episode(name: "The Wars to Come", overview: "Cersei and Jaime adjust to a world without Tywin. Varys reveals a conspiracy to Tyrion. Dany faces a new threat to her rule. Jon is caught between two kings.", airDate: Date.fromString(date: "2015/04/12")!, poster:#imageLiteral(resourceName: "episode5x01.jpg"), season: season5),
            Episode(name: "The House of Black and White", overview: "Arya arrives in Braavos. Podrick and Brienne run into trouble on the road. Cersei fears for her daughter's safety in Dorne as Ellaria Sand seeks revenge for Oberyn's death. Stannis tempts Jon. An adviser tempts Daenerys.", airDate: Date.fromString(date: "2015/04/19")!, poster:#imageLiteral(resourceName: "episode5x02.jpg"), season: season5),
            Episode(name: "High Sparrow", overview: "In Braavos, Arya sees the Many-Faced God. In King's Landing, Queen Margaery enjoys her new husband. Tyrion and Varys walk the Long Bridge of Volantis.", airDate: Date.fromString(date: "2015/04/26")!, poster:#imageLiteral(resourceName: "episode5x03.jpg"), season: season5),
            Episode(name: "Sons of the Harpy", overview: "The Faith Militant grow increasingly aggressive. Jaime and Bronn head south. Ellaria and the Sand Snakes vow vengeance.", airDate: Date.fromString(date: "2015/05/03")!, poster:#imageLiteral(resourceName: "episode5x04.jpg"), season: season5),
            Episode(name: "Kill the Boy", overview: "Dany makes a difficult decision in Meereen. Jon recruits the help of an unexpected ally. Brienne searches for Sansa. Theon remains under Ramsay's control.", airDate: Date.fromString(date: "2015/05/10")!, poster:#imageLiteral(resourceName: "episode5x05.jpg"), season: season5),
            Episode(name: "Unbowed, Unbent, Unbroken", overview: "Arya trains. Jorah and Tyrion run into slavers. Trystane and Myrcella make plans. Jaime and Bronn reach their destination. The Sand Snakes attack.", airDate: Date.fromString(date: "2015/05/17")!, poster:#imageLiteral(resourceName: "episode5x06.jpg"), season: season5),
            Episode(name: "The Gift", overview: "Jon prepares for conflict. Sansa tries to talk to Theon. Brienne waits for a sign. Stannis remains stubborn. Jaime attempts to reconnect with family.", airDate: Date.fromString(date: "2015/05/24")!, poster:#imageLiteral(resourceName: "episode5x07.jpg"), season: season5),
            Episode(name: "Hardhome", overview: "Arya makes progress in her training. Sansa confronts an old friend. Cersei struggles. Jon travels.", airDate: Date.fromString(date: "2015/05/31")!, poster:#imageLiteral(resourceName: "episode5x08.jpg"), season: season5),
            Episode(name: "The Dance of Dragons", overview: "Stannis confronts a troubling decision. Jon returns to The Wall. Mace visits the Iron Bank. Arya encounters someone from her past. Dany reluctantly oversees a traditional celebration of athleticism.", airDate: Date.fromString(date: "2015/06/07")!, poster:#imageLiteral(resourceName: "episode5x09.jpg"), season: season5),
            Episode(name: "Mother's Mercy", overview: "Stannis marches. Dany is surrounded by strangers. Cersei seeks forgiveness. Jon is challenged.", airDate: Date.fromString(date: "2015/06/14")!, poster:#imageLiteral(resourceName: "episode5x10.jpg"), season: season5)
        )
        
        season6.add(episodes:
            Episode(name: "The Red Woman", overview: "The fate of Jon Snow is revealed. Daenerys meets a strong man. Cersei sees her daughter once again.", airDate: Date.fromString(date: "2016/04/24")!, poster:#imageLiteral(resourceName: "episode6x01.jpg"), season: season6),
            Episode(name: "Home", overview: "Bran trains with the Three-Eyed Raven. In King’s Landing, Jaime advises Tommen. Tyrion demands good news, but has to make his own. At Castle Black, the Night’s Watch stands behind Thorne. Ramsay Bolton proposes a plan, and Balon Greyjoy entertains other proposals.", airDate: Date.fromString(date: "2016/05/01")!, poster:#imageLiteral(resourceName: "episode6x02.jpg"), season: season6),
            Episode(name: "Oathbreaker", overview: "Daenerys meets her future. Bran meets the past. Tommen confronts the High Sparrow. Arya trains to be No One. Varys finds an answer. Ramsay gets a gift.", airDate: Date.fromString(date: "2016/05/08")!, poster:#imageLiteral(resourceName: "episode6x03.jpg"), season: season6),
            Episode(name: "Book of the Stranger", overview: "Tyrion strikes a deal. Jorah and Daario undertake a difficult task. Jaime and Cersei try to improve their situation.", airDate: Date.fromString(date: "2016/05/15")!, poster:#imageLiteral(resourceName: "episode6x04.jpg"), season: season6),
            Episode(name: "The Door", overview: "Tyrion seeks a strange ally. Bran learns a great deal. Brienne goes on a mission. Arya is given a chance to prove herself.", airDate: Date.fromString(date: "2016/05/22")!, poster:#imageLiteral(resourceName: "episode6x05.jpg"), season: season6),
            Episode(name: "Blood of My Blood", overview: "An old foe comes back into the picture. Gilly meets Sam’s family. Arya faces a difficult choice. Jaime faces off against the High Sparrow.", airDate: Date.fromString(date: "2016/05/29")!, poster:#imageLiteral(resourceName: "episode6x06.jpg"), season: season6),
            Episode(name: "The Broken Man", overview: "The High Sparrow eyes another target. Jaime confronts a hero. Arya makes a plan. The North is reminded.", airDate: Date.fromString(date: "2016/06/05")!, poster:#imageLiteral(resourceName: "episode6x07.jpg"), season: season6),
            Episode(name: "No One", overview: "While Jaime weighs his options, Cersei answers a request. Tyrion's plans bear fruit. Arya faces a new test.", airDate: Date.fromString(date: "2016/06/12")!, poster:#imageLiteral(resourceName: "episode6x08.jpg"), season: season6),
            Episode(name: "Battle of the Bastards", overview: "As the Starks prepare to fight, Davos loses something dear. Ramsay plays a game. Daenerys faces a choice.", airDate: Date.fromString(date: "2016/06/19")!, poster:#imageLiteral(resourceName: "episode6x09.jpg"), season: season6),
            Episode(name: "The Winds of Winter", overview: "Tyrion counsels Daenerys on the upcoming campaign. Jon and Sansa discuss their future. Trials begin in King's Landing.", airDate: Date.fromString(date: "2016/06/26")!, poster:#imageLiteral(resourceName: "episode6x10.jpg"), season: season6)
        )
        
        season7.add(episodes:
            Episode(name: "Dragonstone", overview: "Jon organizes the defense of the North. Cersei  tries to even the odds. Daenerys comes home.", airDate: Date.fromString(date: "2017/07/16")!, poster:#imageLiteral(resourceName: "episode7x01.jpg"), season: season7),
            Episode(name: "Stormborn", overview: "Daenerys receives an unexpected visitor. Jon faces a revolt. Tyrion plans the conquest of Westeros.", airDate: Date.fromString(date: "2017/07/23")!, poster:#imageLiteral(resourceName: "episode7x02.jpg"), season: season7),
            Episode(name: "The Queen's Justice", overview: "Daenerys holds court. Tyrion backchannels. Cersei returns a gift. Jaime learns from his mistakes.", airDate: Date.fromString(date: "2017/07/30")!, poster:#imageLiteral(resourceName: "episode7x03.jpg"), season: season7),
            Episode(name: "The Spoils of War", overview: "Daenerys fights back. Jaime faces an unexpected situation. Arya comes home.", airDate: Date.fromString(date: "2017/08/06")!, poster:#imageLiteral(resourceName: "episode7x04.jpg"), season: season7)
        )
        
        return [season1, season2, season3, season4, season5, season6, season7].sorted()
    }
    
    func season(named: String) -> Season? {
        let season = seasons.filter{$0.name.uppercased() == named.uppercased()}.first
        return season
    }
    
    func seasons(filteredBy: (Season) -> Bool) -> [Season] {
        let filtered = Repository.local.seasons.filter(filteredBy)
        return filtered
    }
}
